# Starting with Numpy

### Installation & Import (Like any Python library)

$ pip install numpy

In [1]:
#load the library and check its version, just to make sure we aren't using an older version
import numpy as np
np.__version__
#'1.16.4'

'1.16.4'

### Creating Arrays

Numpy arrays are homogeneous in nature, i.e., they comprise one data type (integer, float, double, etc.) unlike lists or DataFrames.

In [2]:
#creating arrays
np.zeros(10, dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [3]:
#creating a 3 row x 5 column matrix
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [4]:
#create an array of even space between the given range of values
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### Array Indexing

Python starts indexing at zero, like Java.

In [5]:
x1 = np.array([4, 3, 4, 4, 8, 4])
x1

array([4, 3, 4, 4, 8, 4])

In [6]:
#assess value to index zero
x1[0]

4

In [7]:
#get the last value
x1[-1]

4

In [8]:
x2 = np.random.randint(10, size=(3,4)) #two dimensional array
x2

array([[3, 4, 9, 8],
       [6, 8, 9, 4],
       [9, 9, 4, 6]])

In [9]:
#in a multidimensional array, we need to specify row and column index
#ARRAY_NAME[row_index, col_index]
#1st row and 2nd column value
x2[0,1]

4

In [10]:
#3rd row and last value from the 3rd column
x2[2,-1]

6

In [11]:
#replace value at 0,0 index
x2[0,0] = 12
x2

array([[12,  4,  9,  8],
       [ 6,  8,  9,  4],
       [ 9,  9,  4,  6]])

In [12]:
x2

array([[12,  4,  9,  8],
       [ 6,  8,  9,  4],
       [ 9,  9,  4,  6]])

### Array Slicing

In [13]:
#create a new array from 0-9
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
#from start to 4th position
x[:5]

array([0, 1, 2, 3, 4])

In [15]:
#from 4th to 6th position
x[4:7]

array([4, 5, 6])

In [16]:
#return elements at even place
x[ : : 2]

array([0, 2, 4, 6, 8])

In [17]:
#return elements from first position step by two
x[1::2]

array([1, 3, 5, 7, 9])

In [18]:
#reverse the array
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

### Array Concatenation

In [19]:
#You can concatenate two or more arrays at once.
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
z = [21,21,21]
np.concatenate([x, y,z])

array([ 1,  2,  3,  3,  2,  1, 21, 21, 21])

In [20]:
#You can also use this function to create 2-dimensional arrays.
grid = np.array([[1,2,3],[4,5,6]])
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [21]:
#Using its axis parameter, you can define row-wise(axis=0) or column-wise matrix(axis=1)
np.concatenate([grid,grid],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

Until now, we used the concatenation function of arrays of equal dimension. If you are required to combine a 2D array with 1D array, you can use np.vstack or np.hstack to do the task. 

In [22]:
#stacks array vertically
x = np.array([3,4,5])
grid = np.array([[1,2,3],[17,18,19]])
np.vstack([x,grid])

array([[ 3,  4,  5],
       [ 1,  2,  3],
       [17, 18, 19]])

In [23]:
#Similarly, you can add an array using np.hstack to stack the array horizontally
z = np.array([[9],[9]])
np.hstack([grid,z])

array([[ 1,  2,  3,  9],
       [17, 18, 19,  9]])

We can also split the arrays on defined positions

In [24]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
x1,x2,x3 = np.split(x,[3,6])
print(x1,x2,x3)

[0 1 2] [3 4 5] [6 7 8 9]


In [26]:
grid = np.arange(16).reshape((4,4)) #reshape defines boundaries of matrix
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [27]:
upper,lower = np.vsplit(grid,[2])
print (upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In addition to the functions we learned above, there are several other mathematical functions available in the numpy library such as sum, divide, multiple, abs, power, mod, sin, cos, tan, log, var, min, mean, max, etc. which you can be used to perform basic arithmetic calculations. Feel free to refer to [numpy documentation](https://www.numpy.org/devdocs/) for more information on such functions.